services:
  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
  loki:
    image: grafana/loki:3.5.3
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./monitoring/loki.yaml:/etc/loki/config.yaml:ro
      - loki:/loki
  alloy:
    image: grafana/alloy:v1.10.2
    user: '0'
    command: ["run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy"]
    volumes:
      - ./monitoring/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - alloy:/var/lib/alloy
    depends_on: [loki]
  grafana:
    image: grafana/grafana:12.1.1
    ports: ["127.0.0.1:3000:3000"]
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/dashboards:/var/lib/grafana/dashboards:ro
      - grafana:/var/lib/grafana
    depends_on: [prometheus, loki]
volumes:
  prometheus:
  loki:
  alloy:
  grafana:
