{
 "title": "TextLab",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Принято заданий",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    { "expr": "textlab_jobs_submitted_total", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Заданий в секунду",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "rate(textlab_jobs_submitted_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Задания по статусу",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "targets": [
    { "expr": "textlab_jobs", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Логи приложения",
   "type": "logs",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "{job=\"textlab\",service=~\"backend|worker\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}